<a href="https://colab.research.google.com/github/surua/Activity1/blob/master/Copy_of_Numpy_Array_and_Vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = [6, 7, 8, 9]
print(type(arr))

<class 'list'>


In [ ]:
a = np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
print(a.shape)

(4,)


In [ ]:
print(a.dtype)

int64


In [ ]:
print(a.ndim)

1


In [ ]:
b = np.array ([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.ndim)

2


In [ ]:
b.shape

(2, 3)

In [ ]:
c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])
c +d 

array([[13., 13., 13.],
       [10., 10., 10.]])

In [ ]:
c*d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [ ]:
5/d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [ ]:
c**2


array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

In [ ]:
3/c

array([[0.33333333, 0.375     , 0.42857143],
       [3.        , 1.5       , 1.        ]])

In [ ]:
d**2

array([[16., 25., 36.],
       [81., 64., 49.]])

In [ ]:
a[0]

6

In [ ]:
a[3]

9

In [ ]:
b[0,0]

1

In [ ]:
b[1,2]

6

In [ ]:
c[0,1]

8.0